### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NotMatte** [AMPZNetwork/All-The-Fabric-4#3]
Every time I open the inventory on the server (the default one) the game closes with this error

The game crashed whilst rendering entity in world
Error: java.lang.IllegalArgumentException: Duplicate delegates

**Comment by LabsZero** [comment]
Can you provide the crash report or latest log.

**Comment by NotMatte** [comment]
> 

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-01-29 20:37:34
Description: Rendering entity in world

java.lang.IllegalArgumentException: Duplicate delegates
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_27952(class_918.java:178)
	at net.minecraft.class_970.method_23192(class_970.java:105)
	at net.minecraft.class_970.method_4169(class_970.java:70)
	at net.minecraft.class_970.method_17157(class_970.java:38)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at net.minecraft.class_1007.method_3936(class_1007.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_27952(class_918.java:178)
	at net.minecraft.class_970.method_23192(class_970.java:105)
	at net.minecraft.class_970.method_4169(class_970.java:70)
	at net.minecraft.class_970.method_17157(class_970.java:38)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at net.minecraft.class_1007.method_3936(class_1007.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 356265
	Entity Name: NotMatte
	Entity's Exact location: 4.45, 60.00, 368.58
	Entity's Block location: World: (4,60,368), Section: (at 4,12,0 in 0,3,23; chunk contains blocks 0,-64,368 to 15,319,383), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.06, -0.08, -0.02
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@e9c1281
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (480, 254). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['NotMatte'/356265, l='ClientLevel', x=4.45, y=60.00, z=368.58]]
	Chunk stats: 1024, 522
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 245746316 game time, 237855900 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	pehkui:debug/render/entity: minecraft:player
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, Built-In.zip, Twilight Classic

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1122259176 bytes (1070 MiB) / 2961178624 bytes (2824 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29936.86
	Virtual memory used (MB): 19642.61
	Swap memory total (MB): 13622.75
	Swap memory used (MB): 315.59
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ae2: Applied Energistics 2 12.9.1
			noindium: No Indium? 1.1.0+1.19
		ae2wtlib: AE2WTLib 12.8.4
		almostunified: AlmostUnified 1.19.2-0.3.2
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.62
		auudio: Auudio 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.4
		betteradvancements: Better Advancements 0.2.2.142
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		betternether: Better Nether 7.1.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bewitchment: Bewitchment 1.19-6
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.8.0
			midnightlib: MidnightLib 0.6.1
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		bhmenu: BHMenu-Fabric 1.19-1.3
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.1.11
		borderlessmining: Borderless Mining 1.1.5+1.19
		bwncr: Bad Wither No Cookie Reloaded 3.14.1
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		collective-fabric: Collective (Fabric) 5.22
			fiber: fiber 0.23.0-2
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		cookingforblockheads: Cooking for Blockheads 13.3.0
		defaultoptions: Default Options 15.0.0
		dimheight: All Dimension World Height 1.1.2
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		drippyloadingscreen: Drippy Loading Screen 1.6.6
		elytraslot: Elytra Slot 6.0.0+1.19.2
		entity_texture_features: Entity Texture Features 4.2.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		experiencebugfix: Experience Bug Fix 18
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric-api: Fabric API 0.68.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.2+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.11
		fancymenu: FancyMenu 2.13.0
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmingforblockheads: Farming for Blockheads 11.1.0
		forgeconfigapiport: Forge Config API Port 4.2.9
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.9+mc1.19.2
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.4.4
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		ironchests: Iron Chests: Restocked 3.1.1
			resourcefullib: Resourceful Lib 1.1.15
		jade: Jade 8.6.3
		jamlib: JamLib 0.5.0
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.0beta4
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		konkrete: Konkrete 1.6.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		languagereload: Language Reload 1.4.1
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.3.3
		lithium: Lithium 0.10.4
		logprot: Logprot Mod 1.19-1.9
		mavapi: More Axolotl Variants API 1.0.1
		mavm: More Axolotl Variants Mod 1.2.0
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		modmenu: Mod Menu 4.1.2
		morefrogs: More Frogs 1.19.x-1.2.3-fabric
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		netherportalfix: NetherPortalFix 10.0.0
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		openloader: OpenLoader 15.0.1
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		oxidized: Oxidized 1.7.2
		paradise_lost: Paradise Lost 2.0.2-beta+1.19.2
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.8.0
		patchouli: Patchouli 1.19.2-77-FABRIC
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		polymorph: Polymorph 0.46.1+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		prism: Prism 1.0.3
		quarrymod: Industrial Quarry Mod 1.0.2
		reborncore: Reborn Core 5.4.0
			team_reborn_energy: Energy 2.3.0
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		rightclickharvest: Right Click Harvest 3.0.6
		roughlyenoughitems: Roughly Enough Items 9.1.577
			error_notifier: Error Notifier 1.0.9
		simple-rpc: Simple RPC 3.2.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.10
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.14+mc1.19.2-build.80
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		techreborn: Tech Reborn 5.4.0
		terrablender: TerraBlender 2.0.1.130
		toastmanager: Toast Manager 1.0.1
		trashslot: TrashSlot 12.0.1
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.9
		treeharvester-fabric: Tree Harvester (Fabric) 5.9
		trinkets: Trinkets 3.4.1
		twilightforest: The Twilight Forest 4.2.310
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.0.591+1.19.2
				porting_lib_base: Porting Lib Base 2.0.591+1.19.2
				porting_lib_entity: Porting Lib Entity 2.0.591+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.591+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.591+1.19.2
				porting_lib_models: Porting Lib Models 2.0.591+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.591+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.591+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.591+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.591+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.591+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.0.591+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.0.591+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.0.591+1.19.2
							com_github_llamalad7_mixinextras: MixinExtras 0.1.0-rc5
							porting_lib_constants: Porting Lib Constants 2.0.591+1.19.2
						porting_lib_common: Porting Lib Common 2.0.591+1.19.2
			serialization_hooks: Serialization Hooks 0.3.22
		universal-graves: Universal Graves 2.1.3+1.19.2
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			polymer: Polymer (Core) 0.2.17+1.19.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.5+1.19.1
		wwoo: William Wythers' Overhauled Overworld 3.1.9
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Loaded Shaderpack: ComplementaryShaders_v4.2.1.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.11-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.56, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, resources/Built-In.zip, Twilight Classic
	Current Language: English (United Kingdom)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
```

This is the crash report

**Comment by NotMatte** [comment]
I just now noticed that the game only crashes when I try to open the inventory while wearing any piece of gold armor (in my case I was wearing an enchanted gold helmet)

**Comment by xAWPMASTERx** [comment]
updating iris seems to fix the problem
